import { useEffect } from 'react';

export function PreloadImgs() {
  // LOGIC
  useEffect(() => {
    const urls = [
      "/img/crews/Abu.webp",
      "/img/crews/Agrabah Siblings.webp",
      "/img/crews/Alan Bradley.webp",
      "/img/crews/Aliens.webp",
      "/img/crews/Alistair Krei.webp",
      "/img/crews/Alpha.webp",
      "/img/crews/Amphitryon And Alcmene.webp",
      "/img/crews/Angry Riley.webp",
      "/img/crews/Anon.webp",
      "/img/crews/Anxious Riley.webp",
      "/img/crews/April, May, and June.webp",
      "/img/crews/Ariel's Sisters.webp",
      "/img/crews/AUTO.webp",
      "/img/crews/Axe Goon.webp",
      "/img/crews/B'loon.webp",
      "/img/crews/Bagheera.webp",
      "/img/crews/Bashful.webp",
      "/img/crews/Bernie Kropp.webp",
      "/img/crews/Beta.webp",
      "/img/crews/Big Baby.webp",
      "/img/crews/Bill The Lizard.webp",
      "/img/crews/Billy, Goat, And Gruff.webp",
      "/img/crews/Bing Bong.webp",
      "/img/crews/Black Guards.webp",
      "/img/crews/Bloofy & Pouchy.webp",
      "/img/crews/Bo'Sun.webp",
      "/img/crews/Bomb Voyage.webp",
      "/img/crews/Bonnie And Stu Hopps.webp",
      "/img/crews/Bonnie Anderson.webp",
      "/img/crews/Boo.webp",
      "/img/crews/Bootstrap Bill Turner.webp",
      "/img/crews/Bot Fight Ringleader.webp",
      "/img/crews/Bruni.webp",
      "/img/crews/Bucky The Squirrel.webp",
      "/img/crews/Bulda.webp",
      "/img/crews/Bullseye.webp",
      "/img/crews/BURN-E.webp",
      "/img/crews/Buzzie, Flaps, Ziggy, And Dizzy.webp",
      "/img/crews/Camel-Al.webp",
      "/img/crews/Camel-Os.webp",
      "/img/crews/Captain B. Mccrea.webp",
      "/img/crews/Captain Sao Feng.webp",
      "/img/crews/Captain.webp",
      "/img/crews/Carina Barbossa.webp",
      "/img/crews/Caroline Cow.webp",
      "/img/crews/Cave Of Wonders.webp",
      "/img/crews/CDA Agents.webp",
      "/img/crews/Cerberus.webp",
      "/img/crews/Chaca And Tipo.webp",
      "/img/crews/Charles F. Muntz.webp",
      "/img/crews/Chef Louis.webp",
      "/img/crews/Chi-Fu.webp",
      "/img/crews/Chicha.webp",
      "/img/crews/Chief O'Hara.webp",
      "/img/crews/Chief Tui.webp",
      "/img/crews/Chip 'N Dale.webp",
      "/img/crews/Chip.webp",
      "/img/crews/Christopher Robin.webp",
      "/img/crews/Chuckles.webp",
      "/img/crews/Chunk.webp",
      "/img/crews/Clara Cluck.webp",
      "/img/crews/Clarabelle Cow.webp",
      "/img/crews/Claudette, Laurette And Paulette.webp",
      "/img/crews/Claw Officers.webp",
      "/img/crews/Clown With The Tear-Away Face.webp",
      "/img/crews/Cobra Bubbles.webp",
      "/img/crews/Cogsworth.webp",
      "/img/crews/Colonel.webp",
      "/img/crews/Construction Foreman Tom.webp",
      "/img/crews/Cotton.webp",
      "/img/crews/Cri-Kee.webp",
      "/img/crews/Critters.webp",
      "/img/crews/CY Bugs.webp",
      "/img/crews/Dapper Dans.webp",
      "/img/crews/David Kawena.webp",
      "/img/crews/Deep Dark Secret.webp",
      "/img/crews/Diablo.webp",
      "/img/crews/Dinah.webp",
      "/img/crews/Disgusted Riley.webp",
      "/img/crews/Doc.webp",
      "/img/crews/Dodo.webp",
      "/img/crews/Donkey.webp",
      "/img/crews/Dopey.webp",
      "/img/crews/Dormouse.webp",
      "/img/crews/Dreamfinder.webp",
      "/img/crews/Duck Family.webp",
      "/img/crews/Dug.webp",
      "/img/crews/Duke Of Weselton.webp",
      "/img/crews/Edna Mode.webp",
      "/img/crews/Edward Dillinger Jr..webp",
      "/img/crews/Elephant On A Bicycle.webp",
      "/img/crews/Ennuyé Riley.webp",
      "/img/crews/Erik And Francis.webp",
      "/img/crews/Evelyn Deavor.webp",
      "/img/crews/Fa Zhou.webp",
      "/img/crews/Fairy Godmother.webp",
      "/img/crews/Fat Cat's Gang.webp",
      "/img/crews/Fat Cat.webp",
      "/img/crews/Fifi The Peke.webp",
      "/img/crews/Fifi.webp",
      "/img/crews/Finnick.webp",
      "/img/crews/Flora, Fauna, and Merryweather.webp",
      "/img/crews/Flotsam And Jetsam.webp",
      "/img/crews/Flounder.webp",
      "/img/crews/Foo-Foo.webp",
      "/img/crews/FPS Robot.webp",
      "/img/crews/Francine `Fanny` Cottontail.webp",
      "/img/crews/Frank And Dave.webp",
      "/img/crews/Fritz.webp",
      "/img/crews/Fru Fru.webp",
      "/img/crews/Fungus.webp",
      "/img/crews/Gadget Hackwrench.webp",
      "/img/crews/Gamma.webp",
      "/img/crews/Gaston's Cronies.webp",
      "/img/crews/Gazeem.webp",
      "/img/crews/Gazelle.webp",
      "/img/crews/Gazerbeam.webp",
      "/img/crews/Gem.webp",
      "/img/crews/Gene.webp",
      "/img/crews/General Hologram.webp",
      "/img/crews/General Li.webp",
      "/img/crews/General.webp",
      "/img/crews/Georges And A.J..webp",
      "/img/crews/Georges Sanderson.webp",
      "/img/crews/Gideon Grey.webp",
      "/img/crews/Giggle McDimples.webp",
      "/img/crews/Gilbert Goof.webp",
      "/img/crews/Gilbert Huph.webp",
      "/img/crews/Gillette.webp",
      "/img/crews/Glut.webp",
      "/img/crews/GO-4.webp",
      "/img/crews/Goat.webp",
      "/img/crews/Goon Leader.webp",
      "/img/crews/Gramma Tala.webp",
      "/img/crews/Grand Council Woman.webp",
      "/img/crews/Grand Pabbie.webp",
      "/img/crews/Grandpa And Grandma Flynn.webp",
      "/img/crews/Grimsby.webp",
      "/img/crews/Grumpy.webp",
      "/img/crews/Gus Goose.webp",
      "/img/crews/Hal.webp",
      "/img/crews/Hamm.webp",
      "/img/crews/Happy Riley.webp",
      "/img/crews/Happy.webp",
      "/img/crews/Heihei.webp",
      "/img/crews/Helicopter Pilot.webp",
      "/img/crews/Henry J. Waternoose.webp",
      "/img/crews/Henry Turner.webp",
      "/img/crews/Hera.webp",
      "/img/crews/Hermes.webp",
      "/img/crews/Hero's Duty Troops.webp",
      "/img/crews/Hook Hand.webp",
      "/img/crews/Horace Horsecollar.webp",
      "/img/crews/Horace.webp",
      "/img/crews/Horse.webp",
      "/img/crews/Hot Dog.webp",
      "/img/crews/Huey, Dewey And Louie.webp",
      "/img/crews/Humphrey The Bear.webp",
      "/img/crews/Huntsman.webp",
      "/img/crews/Hydra.webp",
      "/img/crews/Iago.webp",
      "/img/crews/Ian Mercer.webp",
      "/img/crews/Ice Cream Man.webp",
      "/img/crews/Igor.webp",
      "/img/crews/Intergalactic Police.webp",
      "/img/crews/ISO.webp",
      "/img/crews/J. P. Whiskers.webp",
      "/img/crews/James Norrington.webp",
      "/img/crews/Jangles The Clown.webp",
      "/img/crews/Jaq And Gus.webp",
      "/img/crews/Jarvis.webp",
      "/img/crews/Jasper.webp",
      "/img/crews/Jewel.webp",
      "/img/crews/John And Mary.webp",
      "/img/crews/Jordan.webp",
      "/img/crews/Joshamee Gibbs.webp",
      "/img/crews/José Carioca And Panchito.webp",
      "/img/crews/José, Michael, Fritz, And Pierre.webp",
      "/img/crews/Kaa.webp",
      "/img/crews/Kakamora.webp",
      "/img/crews/Kanga.webp",
      "/img/crews/Karen Beverly.webp",
      "/img/crews/Kermit The Frog-Crew.webp",
      "/img/crews/Kevin Flynn.webp",
      "/img/crews/Kevin.webp",
      "/img/crews/Khan.webp",
      "/img/crews/King Agnarr.webp",
      "/img/crews/King Frederic And Queen Arianna.webp",
      "/img/crews/King Hubert.webp",
      "/img/crews/King Louie.webp",
      "/img/crews/King Of Hearts.webp",
      "/img/crews/King Stefan.webp",
      "/img/crews/Kronk.webp",
      "/img/crews/Kumu.webp",
      "/img/crews/Lady Lightbug.webp",
      "/img/crews/Lance Slashblade.webp",
      "/img/crews/Lefou.webp",
      "/img/crews/Lenny.webp",
      "/img/crews/Lew Zealand.webp",
      "/img/crews/Lieutenant Mattias.webp",
      "/img/crews/Lifeguard.webp",
      "/img/crews/Little Yama.webp",
      "/img/crews/Lock, Shock, And Barrel.webp",
      "/img/crews/Lonesome Ghosts.webp",
      "/img/crews/Lord Cutler Beckett.webp",
      "/img/crews/Luki.webp",
      "/img/crews/Lumiere.webp",
      "/img/crews/Lumpy.webp",
      "/img/crews/M-O.webp",
      "/img/crews/Maccus.webp",
      "/img/crews/Magic Carpet.webp",
      "/img/crews/Magic Mirror.webp",
      "/img/crews/Magica De Spell.webp",
      "/img/crews/Major And Bruno.webp",
      "/img/crews/Man-Eating Wreath.webp",
      "/img/crews/March Hare.webp",
      "/img/crews/Markowski.webp",
      "/img/crews/Marshmallow.webp",
      "/img/crews/Marty.webp",
      "/img/crews/Marv.webp",
      "/img/crews/Mata.webp",
      "/img/crews/Maurice.webp",
      "/img/crews/Max.webp",
      "/img/crews/Mayor Lionheart.webp",
      "/img/crews/Meg.webp",
      "/img/crews/Megabot.webp",
      "/img/crews/Melon Merchant.webp",
      "/img/crews/Mertle Edmonds.webp",
      "/img/crews/Millie And Melody Mouse.webp",
      "/img/crews/Mini Maui.webp",
      "/img/crews/Mochi.webp",
      "/img/crews/Monterey Jack.webp",
      "/img/crews/Moppet Girl.webp",
      "/img/crews/Morty And Ferdie Fildmouse.webp",
      "/img/crews/Mr. Big.webp",
      "/img/crews/Mr. Skipperdoo.webp",
      "/img/crews/Mrs. Hasagawa.webp",
      "/img/crews/Mrs. Potts.webp",
      "/img/crews/Ms. Flint.webp",
      "/img/crews/Mummy Boy.webp",
      "/img/crews/Murtogg And Mullroy.webp",
      "/img/crews/Muses.webp",
      "/img/crews/Mushu.webp",
      "/img/crews/Mutant Toys.webp",
      "/img/crews/Nani.webp",
      "/img/crews/Nanny.webp",
      "/img/crews/Nicelanders.webp",
      "/img/crews/Nick Schmidt.webp",
      "/img/crews/Nostalgia.webp",
      "/img/crews/Oaken.webp",
      "/img/crews/Olympian Gods.webp",
      "/img/crews/Orange Bird.webp",
      "/img/crews/Orange Programs.webp",
      "/img/crews/Owl.webp",
      "/img/crews/Pacha.webp",
      "/img/crews/Pain And Panic.webp",
      "/img/crews/Parrot.webp",
      "/img/crews/Pascal.webp",
      "/img/crews/Pedro.webp",
      "/img/crews/Pegasus.webp",
      "/img/crews/Pepe The King Prawn.webp",
      "/img/crews/Pete Ward.webp",
      "/img/crews/Phil.webp",
      "/img/crews/Philippe.webp",
      "/img/crews/Piglet.webp",
      "/img/crews/Pintel And Ragetti.webp",
      "/img/crews/Pleakley.webp",
      "/img/crews/Pluto.webp",
      "/img/crews/PR-T.webp",
      "/img/crews/Prince Achmed.webp",
      "/img/crews/Prince Charming.webp",
      "/img/crews/Prince Phillip.webp",
      "/img/crews/Priscilla.webp",
      "/img/crews/Prison Dog.webp",
      "/img/crews/Professor Norton Nimnul.webp",
      "/img/crews/Pua.webp",
      "/img/crews/Pudge.webp",
      "/img/crews/Punk Bot Fighter.webp",
      "/img/crews/Queen Iduna.webp",
      "/img/crews/Queen Leah.webp",
      "/img/crews/Rabbit.webp",
      "/img/crews/Raccoon.webp",
      "/img/crews/Rajah.webp",
      "/img/crews/Rat Capone.webp",
      "/img/crews/RC.webp",
      "/img/crews/Reuben.webp",
      "/img/crews/Rex.webp",
      "/img/crews/Rick Dicker.webp",
      "/img/crews/Riley's Dad.webp",
      "/img/crews/Riley's Mom.webp",
      "/img/crews/Rizzo The Rat.webp",
      "/img/crews/Robin The Frog.webp",
      "/img/crews/Robot Dog.webp",
      "/img/crews/Rock Crabs.webp",
      "/img/crews/Roo.webp",
      "/img/crews/Rowlf The Dog.webp",
      "/img/crews/Royal Guards Of Arendelle.webp",
      "/img/crews/Roz.webp",
      "/img/crews/Rudy.webp",
      "/img/crews/Rusty McAllister.webp",
      "/img/crews/Sad Riley.webp",
      "/img/crews/Saitine.webp",
      "/img/crews/Salty The Seal.webp",
      "/img/crews/Sam The Eagle.webp",
      "/img/crews/Samuel J. Gopher.webp",
      "/img/crews/Santa Claus.webp",
      "/img/crews/Sarge.webp",
      "/img/crews/Scared Riley.webp",
      "/img/crews/Scooter.webp",
      "/img/crews/Screenslaver.webp",
      "/img/crews/Scuttle.webp",
      "/img/crews/Seahorse Herald.webp",
      "/img/crews/Sebastian.webp",
      "/img/crews/SECUR-T.webp",
      "/img/crews/Sentry.webp",
      "/img/crews/Sergeant Gerson.webp",
      "/img/crews/Sergeant Tibbs.webp",
      "/img/crews/Shansa.webp",
      "/img/crews/Shanti.webp",
      "/img/crews/Shere Khan.webp",
      "/img/crews/Shorty.webp",
      "/img/crews/Simea.webp",
      "/img/crews/Sina.webp",
      "/img/crews/Sirens.webp",
      "/img/crews/Sitron.webp",
      "/img/crews/Sleepy.webp",
      "/img/crews/Slinky Dog.webp",
      "/img/crews/Smitty And Needleman.webp",
      "/img/crews/SMRT-1.webp",
      "/img/crews/Sneezy.webp",
      "/img/crews/Snowgie.webp",
      "/img/crews/Sofia.webp",
      "/img/crews/Sonny Eclipse.webp",
      "/img/crews/Sorceress.webp",
      "/img/crews/Sour Bill.webp",
      "/img/crews/Sparks.webp",
      "/img/crews/Spear Goon.webp",
      "/img/crews/Stan Litwak.webp",
      "/img/crews/Statler And Waldorf.webp",
      "/img/crews/Stretch.webp",
      "/img/crews/Surge Protector.webp",
      "/img/crews/Susan Hegarty.webp",
      "/img/crews/Sven.webp",
      "/img/crews/Sweetums.webp",
      "/img/crews/Tadashi.webp",
      "/img/crews/Tamatoa.webp",
      "/img/crews/Tanglefoot.webp",
      "/img/crews/Ted Pauley.webp",
      "/img/crews/The Beagle Boys.webp",
      "/img/crews/The Doorknob.webp",
      "/img/crews/The Emperor Of China.webp",
      "/img/crews/The Forgetters.webp",
      "/img/crews/The Grand Duke.webp",
      "/img/crews/The Jungle Patrol.webp",
      "/img/crews/The King.webp",
      "/img/crews/The Mayor.webp",
      "/img/crews/The Mechanical Cow.webp",
      "/img/crews/The Prince.webp",
      "/img/crews/The Reluctant Horse.webp",
      "/img/crews/The Sultan-Al.webp",
      "/img/crews/The Sultan-B&B.webp",
      "/img/crews/The Vampire Brothers.webp",
      "/img/crews/The Walrus And The Carpenter.webp",
      "/img/crews/The Yeti.webp",
      "/img/crews/Theme Song Guy.webp",
      "/img/crews/Theodore Groves.webp",
      "/img/crews/Tony Rydinger.webp",
      "/img/crews/Tootsie The Penguin.webp",
      "/img/crews/Toy Duck.webp",
      "/img/crews/Trolls.webp",
      "/img/crews/Tweedledee And Tweedledum.webp",
      "/img/crews/Twitch.webp",
      "/img/crews/Under The Sea Band.webp",
      "/img/crews/Underminer.webp",
      "/img/crews/Ursula's Garden.webp",
      "/img/crews/Vladimir.webp",
      "/img/crews/Weatherby Swann.webp",
      "/img/crews/Webby Vanderquack.webp",
      "/img/crews/Wheezy.webp",
      "/img/crews/Wilbur.webp",
      "/img/crews/Winston Deavor.webp",
      "/img/crews/Wolf Pack.webp",
      "/img/crews/Wolfman.webp",
      "/img/crews/Wynnchel And Duncan.webp",
      "/img/crews/Yama.webp",
      "/img/crews/Yao, Ling, And Chien Po.webp",
      "/img/crews/Yax.webp",
      "/img/crews/Zero.webp",
      "/img/crews/Zeus.webp",
      "/img/crews/Zipper.webp",
      "/img/racers/Aladdin.webp",
      "/img/racers/Alice.webp",
      "/img/racers/Angel.webp",
      "/img/racers/Anger.webp",
      "/img/racers/Anna.webp",
      "/img/racers/Anxiety.webp",
      "/img/racers/Ariel.webp",
      "/img/racers/Aurora.webp",
      "/img/racers/Baloo.webp",
      "/img/racers/Baymax.webp",
      "/img/racers/Beast.webp",
      "/img/racers/Belle.webp",
      "/img/racers/Bo Peep.webp",
      "/img/racers/Buzz Lightyear.webp",
      "/img/racers/Captain Gantu.webp",
      "/img/racers/Carl Fredricksen.webp",
      "/img/racers/Celia Mae.webp",
      "/img/racers/Chip-RR.webp",
      "/img/racers/Cinderella.webp",
      "/img/racers/Cruella De Vil.webp",
      "/img/racers/Cruz Ramirez.webp",
      "/img/racers/Daisy Duck.webp",
      "/img/racers/Dale.webp",
      "/img/racers/Dash.webp",
      "/img/racers/Davy Jones.webp",
      "/img/racers/Disgust.webp",
      "/img/racers/Donald Duck.webp",
      "/img/racers/Dr. Finkelstein.webp",
      "/img/racers/Eeyore.webp",
      "/img/racers/Elizabeth Swann.webp",
      "/img/racers/Elsa.webp",
      "/img/racers/Emperor Zurg.webp",
      "/img/racers/Ennui.webp",
      "/img/racers/EVE.webp",
      "/img/racers/Fear.webp",
      "/img/racers/Figment.webp",
      "/img/racers/Fix-it Felix.webp",
      "/img/racers/Flash.webp",
      "/img/racers/Forky.webp",
      "/img/racers/Fozzie Bear.webp",
      "/img/racers/Frozone.webp",
      "/img/racers/Gaston.webp",
      "/img/racers/Genie.webp",
      "/img/racers/Go Go Tomago.webp",
      "/img/racers/Goofy.webp",
      "/img/racers/Hades.webp",
      "/img/racers/Hans.webp",
      "/img/racers/Hector Barbossa.webp",
      "/img/racers/Hercules.webp",
      "/img/racers/Hiro.webp",
      "/img/racers/Honey Lemon.webp",
      "/img/racers/Jack Skellington.webp",
      "/img/racers/Jack Sparrow.webp",
      "/img/racers/Jafar.webp",
      "/img/racers/Jasmine.webp",
      "/img/racers/Jessie.webp",
      "/img/racers/Joy.webp",
      "/img/racers/Judy Hopps.webp",
      "/img/racers/Jumba.webp",
      "/img/racers/Kermit the Frog.webp",
      "/img/racers/King Candy.webp",
      "/img/racers/King Triton.webp",
      "/img/racers/Kristoff.webp",
      "/img/racers/Kuzco.webp",
      "/img/racers/Lightning McQueen.webp",
      "/img/racers/Lilo.webp",
      "/img/racers/Lotso.webp",
      "/img/racers/Mabel.webp",
      "/img/racers/Mad Hatter.webp",
      "/img/racers/Maleficent.webp",
      "/img/racers/Maui.webp",
      "/img/racers/Meg.webp",
      "/img/racers/Mickey Mouse.webp",
      "/img/racers/Mike Wazowski.webp",
      "/img/racers/Minnie Mouse.webp",
      "/img/racers/Miss Piggy.webp",
      "/img/racers/Moana.webp",
      "/img/racers/Mowgli.webp",
      "/img/racers/Mr. Incredible.webp",
      "/img/racers/Mrs. Incredible.webp",
      "/img/racers/Mulan.webp",
      "/img/racers/Nick Wilde.webp",
      "/img/racers/Olaf.webp",
      "/img/racers/Oogie Boogie.webp",
      "/img/racers/Ortensia.webp",
      "/img/racers/Oswald.webp",
      "/img/racers/Prince Eric.webp",
      "/img/racers/Queen Of Hearts.webp",
      "/img/racers/Quorra.webp",
      "/img/racers/Ralph.webp",
      "/img/racers/Randall.webp",
      "/img/racers/Rapunzel.webp",
      "/img/racers/Rinzler.webp",
      "/img/racers/Russell.webp",
      "/img/racers/Sadness.webp",
      "/img/racers/Sally.webp",
      "/img/racers/Sam Flynn.webp",
      "/img/racers/Scrooge McDuck.webp",
      "/img/racers/Sergeant Calhoun.webp",
      "/img/racers/Shang.webp",
      "/img/racers/Snow White.webp",
      "/img/racers/Steamboat Mickey.webp",
      "/img/racers/Steamboat Pete.webp",
      "/img/racers/Stitch.webp",
      "/img/racers/Sulley.webp",
      "/img/racers/The Evil Queen.webp",
      "/img/racers/Tia Dalma.webp",
      "/img/racers/Tigger.webp",
      "/img/racers/Tow Mater.webp",
      "/img/racers/Ursula.webp",
      "/img/racers/Vanellope.webp",
      "/img/racers/Violet.webp",
      "/img/racers/WALL-E.webp",
      "/img/racers/Will Turner.webp",
      "/img/racers/Winnie The Pooh.webp",
      "/img/racers/Woody.webp",
      "/img/racers/Yzma.webp",
      "/img/racers/Zuse.webp"
];

    urls.forEach((src) => {
      const img = new Image();
      img.src = src;
    });
  }, []);

  // TEMPLATE
  return <></>;
}